DROP DATABASE IF EXISTS PASTELERIA;
CREATE DATABASE PASTELERIA;
USE PASTELERIA;

CREATE TABLE CATEGORIA(
cveCategoria CHAR(1) PRIMARY KEY NOT NULL,
nomCategoria VARCHAR(25) NOT NULL
);
CREATE TABLE PASTEL(
cvePas CHAR(6) PRIMARY KEY NOT NULL,
nomPas VARCHAR(25) NOT NULL,
cveCategoria CHAR(1) NOT NULL,
FOREIGN KEY (cveCategoria) REFERENCES CATEGORIA (cveCategoria)
ON UPDATE CASCADE
);
INSERT INTO CATEGORIA VALUES('T','PASTELES TRADICIONALES');
INSERT INTO CATEGORIA VALUES('E','PEDIDOS ESPECIALES');
INSERT INTO CATEGORIA VALUES('B','BODAS');
INSERT INTO CATEGORIA VALUES('Q','FIESTAS DE XV');
INSERT INTO CATEGORIA VALUES('I','INFANTILES');